# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AmzrK2
email: amzrk2@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amzrk2.cc" # the base hostname & protocol for your site, e.g. http://example.com

# Social network
twitter_username: AmzrK2
github_username: amzrk2

# Utterances
utterances_repo: amzrk2/utterances-dedicated
utterances_issue_term: pathname
utterances_theme: github-light

# Google Analytics
google_analytics: UA-146011233-1

# Markdown settings, e.g. https://jekyllrb.com/docs/configuration/markdown/
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

# Plugins
plugins:
  - jekyll-sitemap

# Exclude from processing
# The following items will not be processed by default
# Create a custom list to override the default setting
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
